/*
 * The MIT License
 *
 * Copyright 2016 Miguel Angel.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ui;

import data.Player;
import java.awt.Graphics;

/**
 *
 * @author Miguel Angel
 */
public class PlayerInfoPanel extends javax.swing.JPanel {

    Player player;

    /**
     * Creates new form userInfoPanel
     */
    public PlayerInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsLabel = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(150, 70));
        setMinimumSize(new java.awt.Dimension(150, 70));
        setPreferredSize(new java.awt.Dimension(150, 70));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardsLabel.setText("Cards");
        add(cardsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        creditsLabel.setText("Credits");
        add(creditsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        playerNameLabel.setText("PlayerName");
        add(playerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardsLabel;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JLabel playerNameLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (player != null) {
            this.creditsLabel.setText(player.getCredits() + "");
            this.playerNameLabel.setText(player.getName());
            if (player.isHumanPlayer()) {
                for (int i = 0; i < player.getHand().getCards().size(); i++) {
                    player.getHand().getCard(i).paint(g, cardsLabel.getX() + i * 30, cardsLabel.getY() + 10);
                }
            }
            cardsLabel.setText("");
        }
    }

    public void setPlayer(Player player) {
        this.player = player;
    }

}
