/*
 * The MIT License
 *
 * Copyright 2016 Diana.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ui;

import business.GameEngine;
import data.Table;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Diana
 */
public class UISwing extends javax.swing.JFrame implements UI {

    /**
     * Creates new form GUI1
     */
    public UISwing() {
        try {
            initComponents();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            this.setBackground(Color.black);
            SwingUtilities.updateComponentTreeUI(this);
            //this.setIconImage(new ImageIcon(getClass().getResource("/ui/resources/poker.png")));
            this.pack();
            this.setVisible(true);

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        handsButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        roundMenuButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        roundPanel = new javax.swing.JPanel();
        startRoundButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        cardsLabel = new javax.swing.JLabel();
        cards = new javax.swing.JLabel();
        allInButton = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        raiseButton = new javax.swing.JButton();
        callButton = new javax.swing.JButton();
        retireButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UN'Hold Em");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/Users-Exit-icon.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        exitButton.setContentAreaFilled(false);
        exitButton.setOpaque(true);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        cardPanel.setMaximumSize(new java.awt.Dimension(500, 600));
        cardPanel.setMinimumSize(new java.awt.Dimension(500, 600));
        cardPanel.setPreferredSize(new java.awt.Dimension(500, 600));
        cardPanel.setLayout(new java.awt.CardLayout());

        welcomePanel.setBackground(new java.awt.Color(0, 0, 0));
        welcomePanel.setMaximumSize(new java.awt.Dimension(500, 600));
        welcomePanel.setMinimumSize(new java.awt.Dimension(500, 500));
        welcomePanel.setPreferredSize(new java.awt.Dimension(500, 600));

        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/UN Hold'em LOGO.png"))); // NOI18N
        titleLabel.setMaximumSize(new java.awt.Dimension(300, 250));

        helpButton.setBackground(new java.awt.Color(0, 153, 0));
        helpButton.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(255, 255, 255));
        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/Very-Basic-Help-icon.png"))); // NOI18N
        helpButton.setText("Never Played Poker Before?");
        helpButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0)));
        helpButton.setContentAreaFilled(false);
        helpButton.setOpaque(true);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        handsButton.setBackground(new java.awt.Color(204, 102, 0));
        handsButton.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        handsButton.setForeground(new java.awt.Color(255, 255, 255));
        handsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/poker.png"))); // NOI18N
        handsButton.setText("Hands");
        handsButton.setContentAreaFilled(false);
        handsButton.setOpaque(true);
        handsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handsButtonActionPerformed(evt);
            }
        });

        infoButton.setBackground(new java.awt.Color(0, 102, 204));
        infoButton.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        infoButton.setForeground(new java.awt.Color(255, 255, 255));
        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/sign-info-icon.png"))); // NOI18N
        infoButton.setText("Info");
        infoButton.setContentAreaFilled(false);
        infoButton.setOpaque(true);
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        roundMenuButton.setText("Show Round Menu");
        roundMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundMenuButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setBackground(new java.awt.Color(0, 0, 0));
        welcomeLabel.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome to ...");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, welcomePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(welcomePanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addContainerGap(104, Short.MAX_VALUE)
                        .addComponent(helpButton)
                        .addGap(103, 103, 103)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoButton)
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addComponent(handsButton)
                        .addGap(177, 177, 177))))
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(roundMenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(roundMenuButton)
                .addGap(18, 18, 18)
                .addComponent(helpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(handsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        cardPanel.add(welcomePanel, "WELCOMEPANEL");

        roundPanel.setBackground(new java.awt.Color(0, 0, 0));
        roundPanel.setMaximumSize(new java.awt.Dimension(500, 600));
        roundPanel.setMinimumSize(new java.awt.Dimension(500, 600));
        roundPanel.setPreferredSize(new java.awt.Dimension(500, 600));

        startRoundButton.setText("Start Round");
        startRoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startRoundButtonActionPerformed(evt);
            }
        });

        logTextArea.setColumns(35);
        logTextArea.setRows(15);
        scrollPane.setViewportView(logTextArea);

        cardsLabel.setText("Cards");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardsLabel)
                    .addComponent(cards))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cards)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        allInButton.setText("All in");
        allInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allInButtonActionPerformed(evt);
            }
        });

        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        raiseButton.setText("Raise");
        raiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseButtonActionPerformed(evt);
            }
        });

        callButton.setText("Call");
        callButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callButtonActionPerformed(evt);
            }
        });

        retireButton.setText("Retire");
        retireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retireButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanelLayout = new javax.swing.GroupLayout(roundPanel);
        roundPanel.setLayout(roundPanelLayout);
        roundPanelLayout.setHorizontalGroup(
            roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelLayout.createSequentialGroup()
                .addGroup(roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(startRoundButton))
                    .addGroup(roundPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanelLayout.createSequentialGroup()
                                .addComponent(callButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(raiseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allInButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(retireButton))
                            .addGroup(roundPanelLayout.createSequentialGroup()
                                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        roundPanelLayout.setVerticalGroup(
            roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(startRoundButton)
                .addGap(18, 18, 18)
                .addGroup(roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(callButton)
                    .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raiseButton)
                    .addComponent(allInButton)
                    .addComponent(retireButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        cardPanel.add(roundPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exitButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 105, Short.MAX_VALUE)
                    .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exitButton)
                .addContainerGap(583, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        printExit();
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Necesitas Ayuda?");
    }//GEN-LAST:event_helpButtonActionPerformed

    private void handsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handsButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Las manos son...");
    }//GEN-LAST:event_handsButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Desarrollado por..");
    }//GEN-LAST:event_infoButtonActionPerformed

    private void roundMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundMenuButtonActionPerformed
        ((CardLayout) (cardPanel.getLayout())).next(cardPanel);
    }//GEN-LAST:event_roundMenuButtonActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkButtonActionPerformed

    private void raiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raiseButtonActionPerformed

    private void startRoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startRoundButtonActionPerformed
        startRoundButton.setEnabled(false);
        GameEngine.startRound();
    }//GEN-LAST:event_startRoundButtonActionPerformed

    private void allInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allInButtonActionPerformed

    private void callButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_callButtonActionPerformed

    private void retireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retireButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retireButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UISwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UISwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UISwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UISwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UISwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allInButton;
    private javax.swing.JButton callButton;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel cards;
    private javax.swing.JLabel cardsLabel;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton handsButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JButton raiseButton;
    private javax.swing.JButton retireButton;
    private javax.swing.JButton roundMenuButton;
    private javax.swing.JPanel roundPanel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton startRoundButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public String askMsg(String question) throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void printWelcome() {
        JOptionPane.showMessageDialog(this.rootPane, "Hola", "Welcome to UN Hold'em", JOptionPane.PLAIN_MESSAGE);
    }

    @Override
    public void printError(Exception ex) {
        ex.printStackTrace();
        String error = ex.getMessage();
        JOptionPane.showMessageDialog(rootPane,
                ex,
                error,
                JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void printHelp() {
        String msg = "Poker Hold'em is a game of bets in which each player has two cards and the goal is to assemble the \n"
                + " best set of five cards between yours and the five comunitary cards.\n"
                + "The comunitary cards are showed to all the players in this way: After each round of bets, a card \n"
                + " of the deck is 'burned'(discarded)\n"
                + "and three cards(first round) or one card(other rounds) are showed until five cards were at sight.\n"
                + "You can match the bet, backing out, or check (pass) on your turn\n"
                + "bet more if you have a good hand in the game and win more points ";
        JOptionPane.showMessageDialog(rootPane, msg, "Help", JOptionPane.QUESTION_MESSAGE);
    }

    @Override
    public void printCommands() {
    }

    @Override
    public void printHands() {
    }

    @Override
    public void printRoundMenu() {

    }

    @Override
    public void printExit() {
        JOptionPane.showMessageDialog(rootPane, "Hasta luego..");
    }

    @Override
    public void printInfo() {
    }

    @Override
    public void printRoundStandings(Table table, int winners) {
    }

    @Override
    public void printStandings(Table table) {
    }

    @Override
    public void printUser(Table table) {
        cards.setText(table.getPlayerHand(0).toString());
        printMsg("***********************\n"
                + "Cards\tCredits\n"
                + table.getPlayerHand(0) + "\t" + table.getPlayer(0).getCredits() + "\n"
                + "Minimum bet: " + table.getMinBet() + "\n"
                + "***********************\n");
    }

    @Override
    public void printMsg(String msg) {
        synchronized (this) {
            logTextArea.append(msg + "\n");
            logTextArea.setCaretPosition(logTextArea.getDocument().getLength());
        }
    }

    @Override
    public int askMenuOption() {
        return 0;
    }

    @Override
    public int askRoundMenu() {
        setRoundButtonsEnabled(true);
        return 1;
    }

    @Override
    public void printMainMenu(Boolean flag) {
    }

    @Override
    public int askInt(String question) {
        //incompleto
        int result = Integer.parseInt(JOptionPane.showInputDialog(question));
        return result;
    }

    private void setRoundButtonsEnabled(boolean foo) {
        checkButton.setEnabled(foo);
        callButton.setEnabled(foo);
        raiseButton.setEnabled(foo);
        allInButton.setEnabled(foo);
        retireButton.setEnabled(foo);
        
    }

}
